### ISSUE TITLE
Problem when the variant is defined in capital letters

### ISSUE THREAD

**Issue by neuralassembly** [raspberrypi/lxkeymap#2]
## Problem

When I choose the following layout and then I close the lxkeymap, 
lxkeymap fails to launch for the next configuration.
* Country: Japan
* Variant: Japanese(OADG 109A)

## Cause

The variant of "Japanese(OADG 109A)" is defined as "OADG109A", i.e., in capital letters.
Therefore, lxlaunch fails to seach it with the following code.

line 397
`if model.get_value(iter, 1).lower() == matched_text:`

In the above code, "model.get_value(iter, 1).lower()" is "oadg109a", 
and "matched_text" is "OADG109A".

## Solution

The above problem will be solved with the following patch.
If you can accept it, I wiil create a pull request.

    --- lxkeymap.bak        2016-02-17 13:22:48.754328850 +0900
    +++ lxkeymap    2016-02-17 13:23:03.014328845 +0900
    @@ -394,7 +394,7 @@
         #        self.default_path = path
    
         def return_path(self,model,path,iter,matched_text):
    -        if model.get_value(iter, 1).lower() == matched_text:
    +        if model.get_value(iter, 1).lower() == matched_text.lower():
                 self.default_path = path
    
         def generate_variant_list(self):

**Comment by spl237** [comment]
Yes, looks like a good change; please generate a pull request and I'll bring it in. Many thanks.

**Comment by neuralassembly** [comment]
Will this modification be merged in the next Raspbian?

**Comment by spl237** [comment]
Yes, absolutely!

**Comment by neuralassembly** [comment]
Thanks!
