### ISSUE TITLE
The version of lxkeymap is old in the current Raspbian

### ISSUE THREAD

**Issue by neuralassembly** [raspberrypi/lxkeymap#4]
After the modification of lxkeymap on 2016-02-18, the two versions of Raspbian were released, i.e., 2016-02-26 and 2016-03-18. 

However, the version of lxkeymap is still old in both Raspbian.

Do you know when the new lxkeymap is merged into the Raspbian?

**Comment by spl237** [comment]
It's planned to make it into apt over the next few weeks, along with a bunch of other UI changes; we were in pre-release freeze for the 26/2 release when the changes were first pulled, and the release this week was kernel fixes only.
